### ISSUE TITLE
Suggestions for the Site

### ISSUE THREAD

**Issue by HayatoTenryuu** [vbup-osc/ayame-button#1]
Hello! I am Hayato Tenryuu, and I am a big fan of Nakiri Ayame. I have helped with the Pekora button recently (specifically with English and Japanese translation for each of her sound effects), and I have come to offer my fullest support for my favorite VTuber.

I have a few suggestions for the page. First of all, I want to mention things that we updated with Pekora's page: it has Chinese, Japanese, and English translations. I can help with that! My Mandarin Chinese is rough, but it's there. My Japanese is pretty good, and my native language is English, so I can definitely help out there. Also, the Pekora page recently got parallel mp3 and wav file setup, and I noticed that the audio loaded much quicker and better than just the wav files alone. It's just a suggestion, but I think it would help this site too.

I know there is the translation button on the top right, but Pekora found her button's site, and at the time, it defaulted to Chinese, and she couldn't read it. I suggested there, and I am suggesting here, that the default language be set to wherever you are from (Japanese for Japan, etc). It's a simple, but very helpful change for those who don't know any Chinese, like much of Hololive. So while you can leave the translation button itself, I think having the page decide on its default language based on the IP address would be helpful for many.

Finally, there's only one button! Hahaha! Ayame has such good laughs, we can perhaps start with a laugh section. There are entire laugh compilations on YouTube for her, and if you use those, you don't need to sit through her streams. 

Here are some short videos you can use. Each one is less than 4 minutes long:

https://www.youtube.com/watch?v=S9FaJVysk_I
(funny)

https://www.youtube.com/watch?v=XsdQguLgvFc
(various Ayame noises)

https://www.youtube.com/watch?v=fvY4zghmHn0
(laughs)

https://www.youtube.com/watch?v=mYShSxnbJlM
(Funny collab)

https://www.youtube.com/watch?v=aTlXCl8NER4
(adorable end and good noises)

https://www.youtube.com/watch?v=RQsB9xU7VFE
(laughs and cute noises)

https://www.youtube.com/watch?v=rlSQ2U25NC8
(Moe Moe Kyun)

https://www.youtube.com/watch?v=O2UcxCnMbTY
(Fear)

Also, I think her Rhythm Heaven stream was full of good content. Here is the link to that: https://www.youtube.com/watch?v=FGe0f7lE-EI

We could optionally provide images for "Ayame faces", because I have begun a small collection of them myself, and they are really adorable. I will attach the pictures here.

Anyway, these are just some suggestions on what we can do to improve the page, feel free to take what you like and ignore the rest.

![0bdff04e6ac17a36caa405a13d147811](https://user-images.githubusercontent.com/67559652/86043640-9debb480-ba0e-11ea-8a51-eac78dff989d.jpg)
<img width="394" alt="1" src="https://user-images.githubusercontent.com/67559652/86043641-9debb480-ba0e-11ea-9361-72ce99006abb.PNG">
<img width="348" alt="2" src="https://user-images.githubusercontent.com/67559652/86043642-9e844b00-ba0e-11ea-8f90-e5e532bee8c3.PNG">
<img width="386" alt="3" src="https://user-images.githubusercontent.com/67559652/86043644-9f1ce180-ba0e-11ea-8546-efdae8571e97.PNG">
<img width="1565" alt="4" src="https://user-images.githubusercontent.com/67559652/86043649-a04e0e80-ba0e-11ea-97f6-6f2224657780.PNG">
<img width="416" alt="5" src="https://user-images.githubusercontent.com/67559652/86043663-a47a2c00-ba0e-11ea-8f76-e6dca8f55ea3.PNG">
<img width="447" alt="6" src="https://user-images.githubusercontent.com/67559652/86043668-a5ab5900-ba0e-11ea-805c-dd710c2abaef.PNG">
![01121e_62f7a24fee2d4c8c811208c6e5305624_mv2_d_2000_1231_s_2](https://user-images.githubusercontent.com/67559652/86043671-a643ef80-ba0e-11ea-88ed-1b9eb6793620.png)
<img width="959" alt="aaa" src="https://user-images.githubusercontent.com/67559652/86043675-a6dc8600-ba0e-11ea-8bbe-50bb3c0c59ff.PNG">
![ad5VnRN_460s](https://user-images.githubusercontent.com/67559652/86043677-a80db300-ba0e-11ea-8a42-cb9c118c8c93.jpg)
<img width="1561" alt="Capture" src="https://user-images.githubusercontent.com/67559652/86043678-a80db300-ba0e-11ea-81ae-c33ca52ea05c.PNG">
<img width="661" alt="dddd" src="https://user-images.githubusercontent.com/67559652/86043682-aa700d00-ba0e-11ea-9638-3231d7a2831c.PNG">
<img width="652" alt="fea" src="https://user-images.githubusercontent.com/67559652/86043687-ab08a380-ba0e-11ea-8ac5-066c8d2b85ef.PNG">
![Hjnbvea](https://user-images.githubusercontent.com/67559652/86043691-ac39d080-ba0e-11ea-90c7-60aabedf78fb.jpg)
![images](https://user-images.githubusercontent.com/67559652/86043693-acd26700-ba0e-11ea-803a-2baee4bcb843.jpg)
![Koikatu_F_20200503193011654_Nakiri-Ayame_StudentDebt](https://user-images.githubusercontent.com/67559652/86043694-acd26700-ba0e-11ea-87a6-f62648a05c53.png)
![l3CzH1T_xyRZ4sPjAL1RlQ8Jx6bW5ad8sIonXbj-Pz4](https://user-images.githubusercontent.com/67559652/86043698-ad6afd80-ba0e-11ea-9e70-18a176771d61.png)
![Nakiri Ayame full 2399040](https://user-images.githubusercontent.com/67559652/86043699-ae039400-ba0e-11ea-8ec6-aaa5ffc3e549.jpg)
![Nakiri Ayame full 2557885](https://user-images.githubusercontent.com/67559652/86043701-ae039400-ba0e-11ea-9736-38971c9c2dd7.jpg)
![Nakiri_Ayame_-_3D_Model_01](https://user-images.githubusercontent.com/67559652/86043703-ae9c2a80-ba0e-11ea-8c4b-b89f293ee563.png)
![nsmbp0x24xf41](https://user-images.githubusercontent.com/67559652/86043710-afcd5780-ba0e-11ea-9000-51f1d63028b8.jpg)
![p3cwrbworl441](https://user-images.githubusercontent.com/67559652/86043711-afcd5780-ba0e-11ea-81e2-97a740f3ba5c.png)
![sLwmLIf](https://user-images.githubusercontent.com/67559652/86043719-b2c84800-ba0e-11ea-97be-9362598736ab.png)
![SYxxIACoG_qct5XuRiN-VaAeHRh-behltGc3n8Zi4mQ](https://user-images.githubusercontent.com/67559652/86043720-b2c84800-ba0e-11ea-812b-8d9f4719dc84.png)
![tumblr_68767f3d24a0853596ba909ecbb7d34f_70e784d3_500](https://user-images.githubusercontent.com/67559652/86043721-b360de80-ba0e-11ea-8742-92e1298dd5cc.png)
![wUjPYNy](https://user-images.githubusercontent.com/67559652/86043723-b360de80-ba0e-11ea-9a08-2f5168614fc4.jpg)
![preview](https://user-images.githubusercontent.com/67559652/86043752-c07dcd80-ba0e-11ea-93fe-e48058888c7d.gif)

**Comment by HayatoTenryuu** [comment]
I'm sorry to add another thing, but I forgot this video as well. It is short, but it has her cute laughs and Zir's purring and meowing. It's a very cute video, full of cute sounds.
https://youtu.be/rzoker2Hm1Q

**Comment by VoiceButtonUnitedProject** [comment]
非常感谢您的建议。VoiceButtonUnitedProject下的所有语音按钮基于夸按钮进行修改，这意味着我们具有随当前设备语言切换而自动选择按钮语言的功能。我们也会积极的添加各个语言的翻译。我们也了解到您有协助翻译的意愿。请问是否可以提供一下您的联系方式呢？
Thank you so much for your suggestions!Voice Button United Projects' Voice Button projects are all based on aqua button,it means that we have the function to change language by the devices' language changing.We will also add the translation of some language.If you can give us a hand,could you please leave us a contact way?

**Comment by HayatoTenryuu** [comment]
Yes! I can be reached via email at umummd@yahoo.com or on Discord at konokaiden#0080. Let me know how I can help, and I'd be glad to!
好！我的电子邮件地址是umummd@yahoo.com，我的Discord是konokaiden#0080. 如果我能帮你，我高兴得帮助你！
